#! /bin/bash
MakeZip(){
    AnykernelPath=../../Anykernel3
    if [ ! -d $AnykernelPath ];then
        mkdir $AnykernelPath
        cd $AnykernelPath
        git clone https://github.com/ZyCromerZ/AnyKernel3 -b master-lancelot .
        git fetch origin master master-lancelot original
        git checkout origin/master && git checkout -b master
        git checkout origin/original && git checkout -b original
        AnykernelPath=$(pwd)
    else
        cd $AnykernelPath
        git reset --hard
        git fetch origin master-lancelot
        git checkout master-lancelot
        git reset --hard origin/master-lancelot
        AnykernelPath=$(pwd)
    fi
    cp -af $MainPath/../../lancelot/out/arch/arm64/boot/Image.gz-dtb $AnykernelPath && rm -f $MainPath/../../lancelot/out/arch/arm64/boot/Image.gz-dtb 
    cp -af anykernel-real.sh anykernel.sh
    sed -i "s/kernel.string=.*/kernel.string=$KERNEL_NAME-$HeadCommit TEST by ZyCromerZ/g" anykernel.sh
    zip -r ../kernel/zip/lancelot/"[$TANGGAL][Lancelot]$KERNEL_NAME-$ZIP_KERNEL_VERSION.zip" ./ -x .git/**\* ./.git ./anykernel-real.sh ./.gitignore ./LICENSE ./README.md ./*.zip 
    cd $MainPath
}
MakeZipMerlin(){
    AnykernelPath=../../Anykernel3
    if [ ! -d $AnykernelPath ];then
        mkdir $AnykernelPath
        cd $AnykernelPath
        git clone https://github.com/ZyCromerZ/AnyKernel3 -b master-merlin .
        git fetch origin master master-merlin original
        git checkout origin/master && git checkout -b master
        git checkout origin/original && git checkout -b original
        AnykernelPath=$(pwd)
    else
        cd $AnykernelPath
        git reset --hard
        git fetch origin master-merlin
        git checkout master-merlin
        git reset --hard origin/master-merlin
        AnykernelPath=$(pwd)
    fi
    cp -af $MainPath/../../lancelot/out/arch/arm64/boot/Image.gz-dtb $AnykernelPath && rm -f $MainPath/../../lancelot/out/arch/arm64/boot/Image.gz-dtb 
    cp -af anykernel-real.sh anykernel.sh
    sed -i "s/kernel.string=.*/kernel.string=$KERNEL_NAME-$HeadCommit TEST by ZyCromerZ/g" anykernel.sh
    zip -r ../kernel/zip/lancelot/"[$TANGGAL][Merlin]$KERNEL_NAME-$ZIP_KERNEL_VERSION.zip" ./ -x .git/**\* ./.git ./anykernel-real.sh ./.gitignore ./LICENSE ./README.md ./*.zip 
    cd $MainPath
}
HeadCommit="$(git log --pretty=format:'%h' -1)"
export ARCH="arm64"
export SUBARCH="arm64"
export KBUILD_BUILD_USER="ZyCromerZ"
export KBUILD_BUILD_HOST="Lnix-$HeadCommit"
export CCACHE_DIR="../../lancelot/ccache"
MainPath=$(pwd)
KERNEL_NAME=$(cat "$MainPath/arch/arm64/configs/$Defconfig" | grep "CONFIG_LOCALVERSION=" | sed 's/CONFIG_LOCALVERSION="-*//g' | sed 's/"*//g' )
ZIP_KERNEL_VERSION="4.14.$(cat "$MainPath/Makefile" | grep "SUBLEVEL =" | sed 's/SUBLEVEL = *//g')$(cat "$(pwd)/Makefile" | grep "EXTRAVERSION =" | sed 's/EXTRAVERSION = *//g')"
GetCore=$(nproc --all)
TANGGAL=$(date +"%m%d")
MAKE="./makeparallel"
rm -rf ../../lancelot/out
Defconfig="lancelot_defconfig"

make -j$(($GetCore))  O=../../lancelot/out ARCH="arm64" SUBARCH="arm64" "$Defconfig"
if [[ ! -z "$1" ]] && [ "$1" == "regen" ] ;then
    cp -af ../../lancelot/out/.config $MainPath/arch/arm64/configs/$Defconfig
else
    make -j$(($GetCore))  O=../../lancelot/out \
                                PATH="../../clang/google-clang/bin:../../gcc/aarch64-linux-android-4.9/bin:../../gcc/arm-linux-androideabi-4.9/bin:${PATH}" \
                                LD_LIBRARY_PATH="../../clang/google-clang/lib64:${LD_LIBRARY_PATH}" \
                                CC="ccache clang" \
                                CROSS_COMPILE=aarch64-linux-android- \
                                CROSS_COMPILE_ARM32=arm-linux-androideabi- \
                                CLANG_TRIPLE=aarch64-linux-gnu-
    [ -e ../../lancelot/out/arch/arm64/boot/Image.gz-dtb ] && MakeZip
fi

rm -rf ../../lancelot/out
Defconfig="merlin_defconfig"
SpectrumFile="None"
KERNEL_NAME=$(cat "$MainPath/arch/arm64/configs/$Defconfig" | grep "CONFIG_LOCALVERSION=" | sed 's/CONFIG_LOCALVERSION="-*//g' | sed 's/"*//g' )
ZIP_KERNEL_VERSION="4.14.$(cat "$MainPath/Makefile" | grep "SUBLEVEL =" | sed 's/SUBLEVEL = *//g')$(cat "$(pwd)/Makefile" | grep "EXTRAVERSION =" | sed 's/EXTRAVERSION = *//g')"
make -j$(($GetCore))  O=../../lancelot/out ARCH="arm64" SUBARCH="arm64" "$Defconfig"
if [[ ! -z "$1" ]] && [ "$1" == "regen" ] ;then
    cp -af ../../lancelot/out/.config $MainPath/arch/arm64/configs/$Defconfig
else
    make -j$(($GetCore))  O=../../lancelot/out \
                                PATH="../../clang/google-clang/bin:../../gcc/aarch64-linux-android-4.9/bin:../../gcc/arm-linux-androideabi-4.9/bin:${PATH}" \
                                LD_LIBRARY_PATH="../../clang/google-clang/lib64:${LD_LIBRARY_PATH}" \
                                CC="ccache clang" \
                                CROSS_COMPILE=aarch64-linux-android- \
                                CROSS_COMPILE_ARM32=arm-linux-androideabi- \
                                CLANG_TRIPLE=aarch64-linux-gnu-
    [ -e ../../lancelot/out/arch/arm64/boot/Image.gz-dtb ] && MakeZipMerlin
fi
rm -rf ../../lancelot/out
Defconfig="shiva_defconfig"
SpectrumFile="None"
KERNEL_NAME=$(cat "$MainPath/arch/arm64/configs/$Defconfig" | grep "CONFIG_LOCALVERSION=" | sed 's/CONFIG_LOCALVERSION="-*//g' | sed 's/"*//g' )
ZIP_KERNEL_VERSION="4.14.$(cat "$MainPath/Makefile" | grep "SUBLEVEL =" | sed 's/SUBLEVEL = *//g')$(cat "$(pwd)/Makefile" | grep "EXTRAVERSION =" | sed 's/EXTRAVERSION = *//g')"
make -j$(($GetCore))  O=../../lancelot/out ARCH="arm64" SUBARCH="arm64" "$Defconfig"
if [[ ! -z "$1" ]] && [ "$1" == "regen" ] ;then
    cp -af ../../lancelot/out/.config $MainPath/arch/arm64/configs/$Defconfig
else
    make -j$(($GetCore))  O=../../lancelot/out \
                                PATH="../../clang/google-clang/bin:../../gcc/aarch64-linux-android-4.9/bin:../../gcc/arm-linux-androideabi-4.9/bin:${PATH}" \
                                LD_LIBRARY_PATH="../../clang/google-clang/lib64:${LD_LIBRARY_PATH}" \
                                CC="ccache clang" \
                                CROSS_COMPILE=aarch64-linux-android- \
                                CROSS_COMPILE_ARM32=arm-linux-androideabi- \
                                CLANG_TRIPLE=aarch64-linux-gnu-
    [ -e ../../lancelot/out/arch/arm64/boot/Image.gz-dtb ] && MakeZipMerlin
fi